### ISSUE TITLE
Rename repo to Jamadar

### ISSUE THREAD

**Issue by ahmadiq** [stakater/Jamadaar#2]
For consistency with spelling of [Chowkidar](https://github.com/stakater/Chowkidar), and slight benefit of shortness, I would suggest let's rename the repo to _Jamadar_

@hazim1093 Will the rename have impact on anything else? What other places will we need a rename? e.g. docker hub?

**Comment by rasheedamir** [comment]
sure @ahmadiq; lets do it

**Comment by kahootali** [comment]
The repo has been renamed to Jamadar. Closing this.
